[tools]
bat = "latest"
eza = "latest"
go = "latest"
jq = "latest"
rust = "latest"
uv = "latest"
pnpm = "latest"
java = "latest"
jj = "latest"
jjui = "latest"
difftastic = "latest"
golangci-lint = "latest"
duckdb = "latest"
delta = "latest"
helix = "latest"
