[tools]
bat = "latest"
eza = "latest"
jq = "latest"
rust = "latest"
uv = "latest"
pnpm = "latest"
java = "latest"
jj = "latest"
jjui = "latest"
difftastic = "latest"
duckdb = "latest"
delta = "latest"
helix = "latest"
node = "latest"
"npm:vite" = "latest"
claude = "latest"
just = "latest"
"go:golang.org/x/tools/gopls" = "0.21.1"

[settings]

[settings.npm]
package_manager = "pnpm"
