# .warp/settings.toml
[appearance]

[appearance.themes]
theme = { custom = { name = "water", path = "/Users/daniel/.warp/themes/water/water.yaml" } }

[appearance.vertical_tabs]
enabled = true

[appearance.text]
notebook_font_size = 14.0
font_size = 13.0
font_name = "Ioskeley Mono"

[appearance.input]

[appearance.window]

[code]

[code.editor]

[code.indexing]

[warp_drive]

[agents]

[agents.third_party]

[agents.warp_agent]

[agents.warp_agent.other]

[agents.warp_agent.input]

[agents.warp_agent.active_ai]

[agents.profiles]

[notifications]

[notifications.preferences]
is_agent_task_completed_enabled = true
is_long_running_enabled = true
is_needs_attention_enabled = true
is_password_prompt_enabled = true
long_running_threshold = 30
mode = "enabled"
play_notification_sound = true

[privacy]

[privacy.secret_redaction]

[terminal]

[terminal.input]
input_box_type_setting = "universal"

[account]

[warpify]

[warpify.ssh]

[general]

[accessibility]
