services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.4.0
    container_name: pocket-id
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - pocketid-data:/app/data
    networks:
      - holonet
volumes:
  pocketid-data:
    name: pocketid-data
    driver: local

networks:
  holonet:
    external: true
