services:
  arcane-agent:
    image: ghcr.io/getarcaneapp/arcane-headless:latest
    container_name: arcane-agent
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    environment:
      - AGENT_MODE=true
      - AGENT_TOKEN=${ARCANE_AGENT_TOKEN:?missing}
      - MANAGER_API_URL=${ARCANE_AGENT_MANAGER_API_URL:?missing}
    # ports:
    #   - "3553:3553"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data

volumes:
  arcane-data:
