services:
  postgres:
    image: postgres:18
    container_name: postgresql
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - holonet
      
volumes:
  postgres-data:
    name: postgres-data
    driver: local
    
networks:
  holonet:
    external: true
