services:
  postgres:
    image: postgres:18
    container_name: postgresql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB:?missing}
      POSTGRES_USER: ${POSTGRES_USER:?missing}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?missing}
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - holonet
volumes:
  postgres-data:
    driver: local
    name: postgres-data

networks:
  holonet:
    external: true
