services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.22.0
    container_name: zerobyte
    restart: unless-stopped
    networks:
      - holonet
    env_file:
      - .env
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    ports:
      - "4096:4096"
    volumes:
      - /etc/localtime:/etc/localtime:ro # access to localtime
      - /var/lib/zerobyte:/var/lib/zerobyte # required by zerobyte
      - ~/.config/rclone:/root/.config/rclone:ro # required for filen rclone
      - /var/lib/docker/volumes:/docker-volumes:ro # pull in docker volumes
networks:
  holonet:
    external: true
