services:
  arcane:
    image: ghcr.io/getarcaneapp/arcane:v1.18.1@sha256:6d8a51ddca2399106ea20da9db17271a91dd97150cada449aba4edce2ae682c2
    container_name: arcane
    restart: unless-stopped
    ports:
      - 3552:3552
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - arcane-data:/app/data
    networks:
      - holonet
    environment:
      - PUID
      - PGID
      - ENCRYPTION_KEY
      - JWT_SECRET
      - APP_URL
      - LOG_LEVEL
      - LOG_JSON
      - OIDC_ENABLED
      - DATABASE_URL
volumes:
  arcane-data:
    name: arcane-data
    driver: local
networks:
  holonet:
    external: true
